### ISSUE TITLE
MQClient() 参数host无法使用 【http://域名:端口/路径】的格式

### ISSUE THREAD

**Issue by Yuan-ZW** [aliyunmq/mq-http-python-sdk#5]
**创建 mq_client 的代码:**
```
from mq_http_sdk.mq_client import MQClient

#初始化 client
mq_client = MQClient(
    "http://xxx.com.cn:8080/rocketmq/nsaddr4client-internal",
    "***AccessKey***",
    "***SecretKey***",
)
```
**结果报了如下错误:**
```
Traceback (most recent call last):
  File "D:/projects/python/log_parse/mq_test.py", line 25, in <module>
    '***SecretKey***',
  File "D:\Python\Anaconda3\lib\site-packages\mq_http_sdk\mq_client.py", line 45, in __init__
    self.http = MQHttp(self.host, logger=logger, is_https=self.is_https)
  File "D:\Python\Anaconda3\lib\site-packages\mq_http_sdk\mq_http.py", line 67, in __init__
    self.conn = MQHTTPConnection(host, connection_timeout=connection_timeout)
  File "D:\Python\Anaconda3\lib\site-packages\mq_http_sdk\mq_http.py", line 14, in __init__
    HTTPConnection.__init__(self, host, port, strict)
  File "D:\Python\Anaconda3\lib\http\client.py", line 841, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "D:\Python\Anaconda3\lib\http\client.py", line 882, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
http.client.InvalidURL: nonnumeric port: '8080/rocketmq/nsaddr4client-internal'
```

这个url对应的是我们公司内网的一个mq服务
我的同事通过tcp协议的 java sdk: ons-client 连接是没有问题的
但 python 的 mq_http_sdk 似乎连 url 路径都解析不了.

请问有什么解决办法吗?

**Comment by aliyunmq** [comment]
请查看控制台-实例管理中的http接入点。
